development: &development
  adapter: postgresql
  encoding: unicode
  database: rumulu_development
  pool: 5
  host: localhost
  username: rumulu
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: rumulu_test
  pool: 5
  host: localhost
  username: rumulu
  password:

production:
 <<: *development
